name: cli-release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    defaults:
      run:
        working-directory: cli
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: cli/go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          workdir: cli
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
